# Generated by Django 3.2 on 2021-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='last_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
