# Generated by Django 3.2 on 2021-05-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(related_name='item', to='auctions.Comment'),
        ),
    ]
