# Generated by Django 3.2 on 2021-05-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(related_name='items', to='auctions.Category'),
        ),
    ]
