# Generated by Django 3.2 on 2021-05-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210515_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='items',
            field=models.ManyToManyField(related_name='category', to='auctions.Auction'),
        ),
    ]
