# Generated by Django 3.2.3 on 2021-08-07 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210807_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='users_watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
