# Generated by Django 3.2.3 on 2021-08-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_users_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='item', to='auctions.Comment'),
        ),
    ]
